<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_front-page-slider',
		'title' => 'اسلایدر صفحه اصلی',
		'fields' => array (
			array (
				'key' => 'field_543bebdeb29b9',
				'label' => 'اسلایدر همراه با توضیحات',
				'name' => 'slider_with_captions',
				'type' => 'true_false',
				'instructions' => 'اگر این قسمت فعال باشد، شما میتوانید برای هر اسلاید توضیحات، عنوان، دسته بندی و دکمه مخصوص خود را تعریف کنید. در غیر این صورت فقط تصاویر نمایش داده خواهند شد.',
				'message' => 'استفاده از توضیحات بر روی اسلایدها',
				'default_value' => 1,
			),
			array (
				'key' => 'field_543be9800cdbb',
				'label' => 'اسلایدها',
				'name' => 'slides',
				'type' => 'repeater',
				'instructions' => 'شما میتوانید اسلایدهای زیادی به صفحه نخست اضافه کنید، هر کدام با توضیحات خاص خود.',
				'sub_fields' => array (
					array (
						'key' => 'field_543be9d60cdbc',
						'label' => 'تصویر اسلاید',
						'name' => 'slide_image',
						'type' => 'image',
						'required' => 1,
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
					array (
						'key' => 'field_543beac80cdbe',
						'label' => 'عنوان اسلاید',
						'name' => 'slide_title',
						'type' => 'text',
						'required' => 1,
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_543bebdeb29b9',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543bea2f0cdbd',
						'label' => 'دسته بندی اسلاید',
						'name' => 'slide_category',
						'type' => 'text',
						'instructions' => 'این متن در بالای عنوان نمایش داده میشود.',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_543bebdeb29b9',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'پروژه های ویژه',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_543beb42d353b',
						'label' => 'متن اسلاید',
						'name' => 'slide_text',
						'type' => 'wysiwyg',
						'conditional_logic' => array (
							'status' => 1,
							'rules' => array (
								array (
									'field' => 'field_543bebdeb29b9',
									'operator' => '==',
									'value' => '1',
								),
							),
							'allorany' => 'all',
						),
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'basic',
						'media_upload' => 'no',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'افزودن اسلاید جدید',
			),
			array (
				'key' => 'field_543cf0cba7847',
				'label' => 'چرخش اتوماتیک',
				'name' => 'auto_cycle',
				'type' => 'true_false',
				'instructions' => 'بصورت اتوماتیک در ابتدای لود صفحه چرخش شروع شود.',
				'message' => 'چرخش اتوماتیک اسلایدها',
				'default_value' => 1,
			),
			array (
				'key' => 'field_543cf169a7848',
				'label' => 'فاصله زمانی چرخه',
				'name' => 'cycle_interval',
				'type' => 'number',
				'instructions' => 'فاصله زمانی چرخه بر حسب میلی ثانیه می‌باشد(1s = 1000ms).',
				'required' => 1,
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_543cf0cba7847',
							'operator' => '==',
							'value' => '1',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => 5000,
				'placeholder' => '',
				'prepend' => '',
				'append' => 'ms',
				'min' => 0,
				'max' => '',
				'step' => 1000,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-front-page-slider.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_main-title-area-background',
		'title' => 'پس زمینه ناحیه عنوان اصلی',
		'fields' => array (
			array (
				'key' => 'field_548ac758c8459',
				'label' => 'تصویر پس زمینه',
				'name' => 'background_image',
				'type' => 'image',
				'save_format' => 'url',
				'preview_size' => 'thumbnail',
				'library' => 'all',
			),
			array (
				'key' => 'field_548ac795c845a',
				'label' => 'موقعیت افقی تصویر پس زمینه',
				'name' => 'background_image_horizontal_position',
				'type' => 'radio',
				'choices' => array (
					'left' => 'راست',
					'center' => 'وسط',
					'right' => 'چپ',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'center',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_548ac96059261',
				'label' => 'موقعیت عمودی تصویر پس زمینه',
				'name' => 'background_image_vertical_position',
				'type' => 'radio',
				'choices' => array (
					'top' => 'بالا',
					'center' => 'وسط',
					'bottom' => 'پایین',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'center',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_548ac7f5c845b',
				'label' => 'وضعیت تکرار تصویر پس زمینه',
				'name' => 'background_image_repeat',
				'type' => 'radio',
				'choices' => array (
					'no-repeat' => 'بدون تکرار',
					'repeat' => 'تکرار (Tile)',
					'repeat-x' => 'تکرار افقی',
					'repeat-y' => 'تکرار عمودی',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'repeat',
				'layout' => 'horizontal',
			),
			array (
				'key' => 'field_548ac864c845c',
				'label' => 'پیوست تصور پس زمینه',
				'name' => 'background_image_attachment',
				'type' => 'radio',
				'choices' => array (
					'scroll' => 'اسکرول',
					'fixed' => 'ثابت',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'scroll',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_548ac899c845d',
				'label' => 'رنگ پس زمینه',
				'name' => 'background_color',
				'type' => 'color_picker',
				'default_value' => '#f2f2f2',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'default',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-builder-page.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 2,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_page-slider',
		'title' => 'اسلایدر صفحه',
		'fields' => array (
			array (
				'key' => 'field_5463508653f33',
				'label' => 'نوع اسلایدر',
				'name' => 'slider_type',
				'type' => 'radio',
				'required' => 1,
				'choices' => array (
					'layer' => 'LayerSlider',
					'revolution' => 'Revolution Slider',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => '',
				'layout' => 'vertical',
			),
			array (
				'key' => 'field_5463511b53f34',
				'label' => 'LayerSlider ID',
				'name' => 'layer_slider_id',
				'type' => 'number',
				'instructions' => 'LayerSlider can be used as alternative slider and doesn\'t come with the theme for free. You can buy it <a href="http://codecanyon.net/item/layerslider-responsive-wordpress-slider-plugin-/1362246?ref=ProteusThemes" target="_blank">here</a>. Paste the ID of the slider you created in the plugin to this box (only ID, not the whole shortcode).',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5463508653f33',
							'operator' => '==',
							'value' => 'layer',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 1,
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_546351d953f35',
				'label' => 'Revolution Slider Alias',
				'name' => 'revolution_slider_alias',
				'type' => 'text',
				'instructions' => 'Slider Revolution can be used as alternative slider and doesn\'t come with the theme for free. You can buy it <a href="http://codecanyon.net/item/slider-revolution-responsive-wordpress-plugin/2751380?ref=ProteusThemes" target="_blank">here</a>. Paste the alias of the slider you created in the plugin to this box (only <a href="https://www.diigo.com/item/image/3rli1/s9bj?size=o" target="_blank">alias</a>, not the whole shortcode).',
				'conditional_logic' => array (
					'status' => 1,
					'rules' => array (
						array (
							'field' => 'field_5463508653f33',
							'operator' => '==',
							'value' => 'revolution',
						),
					),
					'allorany' => 'all',
				),
				'default_value' => '',
				'placeholder' => 'main-slider',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'template-front-page-slider-alt.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'side',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_position-of-the-sidebar',
		'title' => 'موقعیت سایدبار',
		'fields' => array (
			array (
				'key' => 'field_543251af2850a',
				'label' => '',
				'name' => 'sidebar',
				'type' => 'radio',
				'instructions' => 'Position the sidebar for this particular page: left, right or do not display it at all.',
				'choices' => array (
					'right' => 'چپ',
					'left' => 'راست',
					'none' => 'بدون سایدبار',
				),
				'other_choice' => 0,
				'save_other_choice' => 0,
				'default_value' => 'right',
				'layout' => 'horizontal',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '!=',
					'value' => 'template-front-page-slider.php',
					'order_no' => 1,
					'group_no' => 0,
				),
				array (
					'param' => 'page_template',
					'operator' => '!=',
					'value' => 'template-front-page-slider-alt.php',
					'order_no' => 2,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_project-details-and-gallery',
		'title' => 'گالری و جزئیات پروژه',
		'fields' => array (
			array (
				'key' => 'field_544a786faaa9b',
				'label' => 'تاریخ انجام پروژه',
				'name' => 'construction_date',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_544a798caaa9c',
				'label' => 'موقعیت',
				'name' => 'location',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_544a79caaaa9d',
				'label' => 'مساحت',
				'name' => 'surface_area',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_544a7a1eaaa9e',
				'label' => 'سرمایه گذار',
				'name' => 'contracting_investor',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_544a7a91aaa9f',
				'label' => 'مقدار',
				'name' => 'value',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_547c9a1be0dd5',
				'label' => 'دسته بندی',
				'name' => 'category',
				'type' => 'true_false',
				'message' => 'نمایش دسته بندی ها',
				'default_value' => 1,
			),
			array (
				'key' => 'field_546b42a17fec6',
				'label' => 'فیلد اضافی',
				'name' => 'additional_fields',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_54747fc31dbb6',
						'label' => 'آیکن',
						'name' => 'icon',
						'type' => 'text',
						'instructions' => 'Select from the <a href="http://fontawesome.io/icons/" target="_blank">FontAwesome</a> website.',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => 'fa-cogs',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => 40,
					),
					array (
						'key' => 'field_546b42ce7fec7',
						'label' => 'نام',
						'name' => 'name',
						'type' => 'text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_546b42fb7fec8',
						'label' => 'مقدار',
						'name' => 'value',
						'type' => 'text',
						'required' => 1,
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'افزودن فیلد',
			),
			array (
				'key' => 'field_544a7adeaaaa0',
				'label' => 'گالری پروژه',
				'name' => 'project_gallery',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_544a7b0daaaa1',
						'label' => 'تصویر پروژه',
						'name' => 'project_image',
						'type' => 'image',
						'column_width' => '',
						'save_format' => 'id',
						'preview_size' => 'thumbnail',
						'library' => 'all',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'افزودن تصویر',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'portfolio',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'default',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
	register_field_group(array (
		'id' => 'acf_subtitle',
		'title' => 'زیرنویس',
		'fields' => array (
			array (
				'key' => 'field_55472b7e5eaf2',
				'label' => '',
				'name' => 'subtitle',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'Subtitle',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}